== Expressions

[[value-expressions]]
=== Value expressions

An expression is a sequence of tokens to which a type can be assigned, and which evaluates to a well-defined value when the query is executed.
Expressions may be categorized as:

- literals,
- special values,
- parameters,
- enum literals,
- paths,
- function calls,
- quantifiers,
- case expressions, and
- operator expressions.

[[literal-expressions]]
==== Literal expressions

The syntax for literal expressions is given by the rules `string_literal` and `numeric_literal`, and in the previous section titled <<Lexical structure>>.

In an implementation of Jakarta Query for clients written in Java, a string, integer, or decimal literal is assigned the type it would be assigned in Java.
So, for example, `'Hello'` is assigned the type `java.lang.String`, `123` is assigned the type `int`, `1e4` is assigned the type `double`, and `1.23f` is assigned the type `float`.
In the extended language:

- arbitrary-precision integer literals (with suffix `BI`) are assigned the type `java.math.BigInteger`, and
- arbitrary-precision decimal literals (with suffix `BD`) are assigned the type `java.math.BigDecimal`.

When executed, a literal expression evaluates to its literal value.

==== Special values

The syntax for _special values_ is given by the rules `special_boolean_expression` and `special_datetime_expression`.

In an implementation of Jakarta Query for clients written in Java:

- the special values `true` and `false` are assigned the type `boolean`, and
- the special values `local date`, `local time`, and `local datetime` are assigned the types `java.time.LocalDate`, `java.time.LocalTime`, and `java.time.LocalDateTime`.

The expression `true` and `false` evaluate to their literal values.
The expressions `local date`, `local time`, and `local datetime` evaluate to the current date, current time, and current datetime of the database server, respectively.

==== Parameter expressions

A parameter expression, with syntax given by `input_parameter`, is assigned a type and value either:

1. at runtime, via invocation of some API (for example, `setParameter()` in Jakarta Persistence), or
2. at compile type, via static analysis (for example, by inspecting the parameters of a Jakarta Data repository method).

NOTE: This specification does not define how arguments are assigned to parameter expressions.

When executed, a parameter expression evaluates to the argument assigned to the parameter.

Positional and named parameters must not be mixed in a single query.

==== Enum literals

An _enum literal expression_ is a sequence of identifiers, with syntax specified by `enum_literal`, and must refer to a member of some sort of enumerated type.
An enum literal may only occur as:

- the right operand of an `update_item` belonging to a `set` assignment,
- the right operand of an `=` or `<>` equality comparison, or
- an `in_item` element of an `in_item_list` occurring as the right operand of the <<in-expressions,`in` operator>>.

In each case, the enum literal expression is assigned the type of the left operand of the assignment, comparison, or `in` operator.

In an implementation of Jakarta Query for clients written in Java, the type assigned must be a Java `enum` type, and the identifier must be the name of an enumerated value of the `enum` type including the fully qualified Java enum class name. For example, `day <> java.time.DayOfWeek.MONDAY` is a legal comparison expression.

When executed, the enum literal expression evaluates to the named member of the enumerated type.

**TODO** allow `day <> MONDAY`, since the `enum` type can be inferred.

==== Entity type literals

In the extended language, an entity type literal, with syntax given by `#entity_type_literal#` is just the name of an entity type.
When executed, it evaluates to a value which represents the named entity type.

An implementation of Jakarta Query targeting clients written in Java assigns the type `java.lang.Class<E>` to an entity type literal, where `E` is the Java class mapping the named entity type.
When executed, the literal evaluates to an instance of `Class` representing the Java class `E`.

[[path-expressions]]
==== Path expressions

A _path expression_ is a period-separated list of Java identifiers, with syntax specified by `state_field_path_expression`. A path expression is a compound path identifying an element of a structure, as discussed above in <<paths>>. Each identifier is interpreted as the name of an attribute of an entity or embeddable type. Each prefix of the list is assigned a type:

- the first element of the list is assigned the type of the named attribute of the entity being queried, and
- each subsequent element is assigned the type of the named attribute of the type assigned to the previous element.

The type of the whole path expression is the type of the last element of the list. For example, `pages` might be assigned the type `int`, `address` might be assigned the type `org.example.Address`, and `address.street` might be assigned the type `java.lang.String`.

NOTE: Typically, the last element of a path expression is assigned an <<atomic-values,atomic value type>>. Non-terminal path elements are assigned a <<structures-and-records,structure type>>, usually an embeddable type, if the element references an embeddable, or an entity type, if the element references an association. Jakarta EE specifications that use Jakarta Query determine whether a provider is required to support embedded attributes or associations, which require support for compound path expressions.

When a path expression is executed, each element of the path is evaluated in turn:

- the first element of the path expression is evaluated in the context of a given record of the queried entity type, and evaluates to the value of the named entity attribute of the given record, and then
- each subsequent element is evaluated in the context of the result produced the previous element (typically, and embeddable class or associated entity class), and evaluates to the value of the named attribute of the result.

If any element of a path expression evaluates to a null value, the whole path expression evaluates to a null value.

==== Identifier and version expressions

In the core language, an _identifier expression_, with syntax given by `id_expression`, is assigned the type of the unique identifier of the queried entity and evaluates to the unique identifier of a given record. An identifier expression is a synonym for a path expression with one element matching the identifier attribute of the queried entity type. An identifier expression may occur in the `select` clause, in the `order` clause, or as a scalar expression in the `where` clause.

In the extended language, the grammar rule `#entity_id_or_version_function#` gives the syntax of the special functions `id` and `version`, which accept a path expression whose last element is assigned an entity type, and evaluate to, respectively, the identifier or version element of the record to which the path expression evaluates when executed.

==== Function calls

A _function call_ is the name of a function recognized by the Jakarta Query implementation, followed by a parenthesized list of argument expressions, with syntax given by:

- `function_expression` in the core language, or
- `#functions_returning_strings#`, `#functions_returning_datetime#`, and `#functions_returning_numerics#` in the full grammar of the extended language.

This specification defines the standard functions listed in the table below.

NOTE: Functions highlighted in yellow belong to the extended language and are not required for an implementation of the core language.

[cols="15,15,15,15,~"]
|===
| Function name | Parameters | Parameter types | Type | Semantics

| `abs` | 1 | Any numeric type | Same as argument | Evaluates to the absolute value of the numeric value to which its argument evaluates.
| `#sign#` | 1 | Numeric | Integer | Evaluates to the sign (-1, 0, or 1) of the numeric value of its argument.
| `#mod#` | 2 | Both integer | Integer | Evaluates to the remainder when its first integer argument is divided by its second integer argument. The behavior is undefined when either or both of the arguments are negative and depends on the data store that is used.
| `#sqrt#` | 1 | Numeric | Double precision | Evaluates to the positive square root of its numeric argument.
| `#exp#` | 1 | Numeric | Double precision | Evaluates to the natural exponential of its numeric argument.
| `#ln#` | 1 | Numeric | Double precision | Evaluates to the natural logarithm of its numeric argument.
| `#power#` | 2 | Both numeric | Double precision | Evaluates to the value produced by raising its first numeric argument to the power specified by its second numeric argument.
| `#ceiling#` | 1 | Any numeric type | Same as argument | Evaluates to the smallest integral value at least as large as its argument.
| `#floor#` | 1 | Any numeric type | Same as argument | Evaluates to the largest integral value at least as small as its argument.
| `#round#` | 2 | Any numeric type, integer | Same as first argument | Evaluates to the value produced by rounding its first numeric argument with the precision given by its second integer argument.
| `length` | 1 | String | Integer | Evaluates to the length of string to which its argument evaluates.
| `lower` | 1 | String | String | Evaluates to the lowercase form of the string to which its argument evaluates.
| `upper` | 1 | String | String | Evaluates to the uppercase form of the string to which its argument evaluates.
| `left` | 2 | String, integer | String | Evaluates to a prefix of the string to which its first argument evaluates. The length of the prefix is given by the integer value to which its second argument evaluates.
| `right` | 2 | String, integer | String | Evaluates to a suffix of the string to which its first argument evaluates. The length of the suffix is given by the integer value to which its second argument evaluates.
| `#concat#` | At least one | All strings | String | Evaluates to the concatenation of its arguments.
| `#substring#` | 2 or 3 | String, integer, integer | String | Evaluates to a specified substring of the first argument. The second and third arguments specify the starting position and length of the substring. The third argument is optional. If it is not specified, the substring from the starting position to the end of the string is returned. The first character of the string is at position `1`.
| `#trim#` | 1^*^ | String | String | Trims a specified character from its last argument. If the character to be trimmed is not specified, the space character is trimmed. The optional `#trim_character#` specifies the character to be trimmed. The optional `#trim_specification#` controls whether the character is trimmed from the start and/or end of the string. By default, the character is trimmed from both start and end.
| `#replace#` | 3 | All strings | String | Evaluates to a new string formed by replacing every occurrence of the second argument string within the first argument string with the third argument string.
| `#locate#` | 2 or 3 | String, string, integer | Integer | Evaluates to the position at which one string occurs within a second string, optionally ignoring any occurrences that begin before a specified character position in the second string. It returns the first character position within the second string (after the specified character position, if any) at which the first string occurs, as an integer, where the first character of the second string is denoted by 1. That is, the first argument is the string to be searched for; the second argument is the string to be searched in; the optional third argument is an integer representing the character position at which the search starts (by default, 1, the first character of the second string). If the first string does not occur within the second string, 0 is returned.
| `#size#` | 1 | Collection | Integer | Evaluates to the number of elements in the collection to which its argument evaluates.
| `#coalesce#` | At least two | Any atomic type `T` | `T` | Evaluates to the value of the first argument expression which evaluates to a non-null value.
| `#nullif#` | 2 | Any atomic type `T` | `T` | Evaluates to the value of the first argument expression if both argument expressions evaluate to the same value, or to the null value otherwise.
|===

When any argument expression of any function call evaluates to a null value, the whole function call evaluates to null.

NOTE: Some of these functions cannot be emulated on every datastore. When a function cannot be reasonably emulated via the native query capabilities of the database, an implementation of Jakarta Query is not required to provide the function.

NOTE: On the other hand, an implementation of Jakarta Query might provide additional built-in functions, and might even allow invocation of user-defined functions.

An implementation of Jakarta Query for clients written in Java must assign:

- the type `java.lang.String` to every function of type "String",
- the type `java.lang.Integer` to every function of type "Integer", and
- the type `java.lang.Double` to every function of type "Double precision".

The primitive types `double`, `float`, `long`, `int`, `short`, `byte`, wrappers for these primitive types, `BigInteger`, and `BigDecimal` are all considered "Numeric" types.

**TODO** `EXTRACT()`, `INDEX()`, `VALUE()`, `KEY()`, `FUNCTION()`

==== Types and typecasts

The extended language provides three special functions for working with subtype polymorphism.

===== Treated path expressions

A _treated path expression_ is an invocation of the special `#treat()#` function, with syntax given by `#treated_entity_path_expression#` and `#treated_joinable_path_expression#`.
The `#treat()#` function accepts:

1. a <<path-expressions,path expression>> whose last element is assigned an entity type, and
2. the name of an entity type -- called the _treated type_ -- which must be a subtype of the entity type assigned to the path expression.

A treated path expression is assigned the treated type.

When a treated path expression is executed, the record produced by evaluating the path expression is compared to the treated type.

- If the record is an <<entities-embeddables,instance of>> the treated type, the treated path expression evaluates to the record.
- Otherwise, if the record is not an instance of the treated type, the treated path expression evaluates to the null value.

===== Coercion expressions

A _coercion expression_ is an invocation of the special `#cast()#` function, with syntax given by the last alternatives of `#functions_returning_numerics#` and `#functions_returning_strings#`.
The `#cast()#` function accepts:

1. an expression assigned an atomic type, and
2. the name of an atomic type.

A coerced expression is assigned the named atomic type.

When a coercion expression is executed, the atomic value produced by evaluating the path expression is coerced to the named atomic type.

[IMPORTANT]
====
This specification places no specific requirements on the types which are allowed as arguments of the `#cast()#` function, nor on the behavior of coercion between types.
As suggested by the grammar for `#functions_returning_numerics#` and `#functions_returning_strings#`, implementations of the extended language are strongly encouraged to support at least:

- coercion from string to any numeric type, and
- coercion from any atomic type to string.

However, this part of the grammar should be read as indicative of what should be supported in implementations of Jakarta Query which target clients written in Java, and, more specifically, what is required for an implementation of Jakarta Persistence.

The capabilities of the `#cast()#` function vary between client programming languages and between databases.
====

===== Entity type expressions

An _entity type expression_ is an invocation of the special `#type()#` function, with syntax given by `#type_discriminator#`.
The `#type()#` function accepts an expression assigned an entity type, and, when executed, evaluates to a value which represents the type of the record to which the argument expression evaluates.

An implementation of Jakarta Query targeting clients written in Java assigns the type `java.lang.Class<? extends E>` where `E` is the Java class mapping the entity type assigned to the argument expression, and an entity type expression evaluates to an instance of `Class` representing the Java class which maps the entity type of the record to which the argument expression evaluates.

[[quantifiers]]
==== Quantifiers

**TODO** `EXISTS()`, `ALL()`, `ANY()`, `SOME()`

[[case-expressions]]
==== Case expressions

**TODO**

[[operator-expressions]]
==== Operator expressions

The syntax of an _operator expression_ is given by the `scalar_expression` rule. Within an operator expression, parentheses indicate grouping.

All binary infix operators are left-associative. The relative precedence, from highest to lowest precedence, is given by:

1. `*` and `/`,
2. `+` and `-`,
3. `||`.

The unary prefix operators `+` and `-` have higher precedence than the binary infix operators. Thus, `2 * -3 + 5` means `(2 * (-3)) + 5` and evaluates to `-1`.

The concatenation operator `||` is assigned the type `java.lang.String`. Its operand expressions must also be of type `java.lang.String`. When executed, a concatenation operator expression evaluates to a new string concatenating the strings to which its arguments evaluate.

The numeric operators `+`, `-`, `*`, and `/` have the same meaning for primitive numeric types they have in Java, and operator expression involving these operators are assigned the types they would be assigned in Java.

NOTE: As an exception, when the operands of `/` are both integers, an implementation of Jakarta Query is not required to interpret the operator expression as integer division if that is not the native semantics of the database. However, portability is maximized when Jakarta Query providers _do_ interpret such an expression as integer division.

The four numeric operators may also be applied to an operand of wrapper type, for example, to `java.lang.Integer` or `java.lang.Double`. In this case, the operator expression is assigned a wrapper type, and evaluates to a null value when either of its operands evaluates to a null value. When both operands are non-null, the semantics are identical to the semantics of an operator expression involving the corresponding primitive types.

The four numeric operators may also be applied to operands of type `java.math.BigInteger` or `java.math.BigDecimal`.

A numeric operator expression is evaluated according to the native semantics of the database. In translating an operator expression to the native query language of the database, a Jakarta Query provider is encouraged, but not required, to apply reasonable transformations so that evaluation of the expression more closely mimics the semantics of the Java language.

==== Numeric types and numeric type promotion

The type assigned to an operator expression depends on the types of its operand expression, which need not be identical.
Numeric type promotion is defined by the following rules:

* If there is an operand of type `Double` or `double`, the expression is of type `Double`.
* Otherwise, if there is an operand of type `Float` or `float`, the expression is of type `Float`.
* Otherwise, if there is an operand of type `BigDecimal`, the expression is of type `BigDecimal`.
* Otherwise, if there is an operand of type `BigInteger`, the expression is of type `BigInteger`, unless the operator is `/` (division), in which case the expression type is not defined here.
* Otherwise, if there is an operand of type `Long` or `long`, the expression is of type `Long`, unless the operator is `/` (division), in which case the expression type is not defined here.
* Otherwise, if there is an operand of integral type, the expression is of type `Integer`, unless the operator is `/` (division), in which case the expression type is not defined here.

[[predicates]]
=== Conditional expressions

A _conditional expression_ is a sequence of tokens which specifies a condition which, for a given record, might be _satisfied_ or _unsatisfied_. Unlike the scalar <<Expressions>> defined in the previous section, a conditional expression is not considered to have a well-defined type.

NOTE: The Jakarta Persistence specification defines the result of a conditional expression in terms of ternary logic. This specification does not specify that a conditional expression evaluates to well-defined value, only the effect of the conditional expression when it is used as a restriction. The "value" of a conditional expression is not considered observable by the application program.

Conditional expressions may be categorized as:

- `null` comparisons,
- `in` expressions,
- `between` expressions,
- `like` expressions,
- equality and inequality operator expressions, and
- logical operator expressions.

The syntax for conditional expressions is given by the `conditional_expression` rule. Within a conditional expression, parentheses indicate grouping.

==== Null comparisons

A `null` comparison, with syntax given by `null_comparison_expression` is satisfied when:

- the `not` keyword is missing, and its operand evaluates to a null value, or
- the `not` keyword occurs, and its operand evaluates to any non-null value.

[[in-expressions]]
==== In expressions

An `in` expression, with syntax given by `in_expression` is satisfied when its leftmost operand evaluates to a non-null value, and:

- the `not` keyword is missing, and any one of its parenthesized operands evaluates to the same value as its leftmost operand, or
- the `not` keyword occurs, and none of its parenthesized operands evaluate to the same value as its leftmost operand.

All operands must have the same type.

==== Between expressions

A `between` expression, with syntax given by `between_expression` is satisfied when its operands all evaluate to non-null values, and, if the `not` keyword is missing, its left operand evaluates to a value which is:

- larger than or equal to the value taken by its middle operand, and
- smaller than or equal to the value taken by its right operand.

Or, if the `not` keyword occurs, the left operand must evaluate to a value which is:

- strictly smaller than to the value taken by its middle operand, or
- strictly larger than the value taken by its right operand.

All three operands must have the same type.

==== Like expressions

A `like` expression is satisfied when its left operand evaluates to a non-null value and:

- the `not` keyword is missing, and this value matches the pattern, or
- the `not` keyword occurs, and the value does not match the pattern.

The left operand must have type `java.lang.String`.

Within the pattern, `_` matches any single character, and `%` matches any sequence of characters.

==== Equality and inequality operators

The equality and inequality operators are `=`, `&lt;&gt;`, `&lt;`, `&gt;`, `&lt;=`, `&gt;=`.

- For primitive types, these operators have the same meaning they have in Java, except for `<>` which has the same meaning that `!=` has in Java. Such an operator expression is satisfied when the equivalent operator expression would evaluate to `true` in Java.
- For wrapper types, these operators are satisfied if both operands evaluate to non-null values, and the equivalent operator expression involving primitives would be satisfied.
- For other types, these operators are evaluated according to the native semantics of the database.

The operands of an equality or inequality operator must have the same type.

NOTE: Portability is maximized when Jakarta Query providers interpret equality and inequality operators in a manner consistent with the implementation of `Object.equals()` or `Comparable.compareTo()` for the assigned Java type.

[WARNING]
====
When using NoSQL databases, there are limitations to the support of equality and inequality operators:

1. **Key-Value Databases**: Support for the equality restriction on the key attribute is required. The key attribute is defined by the annotation `jakarta.nosql.Id`. Key-value databases are not required to support any other restrictions.

2. **Wide-Column Databases**: Support for equality restriction and the inequality restriction on the `Id` attribute is required. Support for restrictions on other entity attributes is not required. These operations typically work only with the `Id` by default but might be compatible for other entity attributes if secondary indexes are configured in the database schema.

3. **Graph and Document Databases**: Support for all equality and inequality operators is required.
====

=== Ordering

Every <<atomic-values,atomic value type>> can, in principle, be equipped with a total order. An order for a type determines the result of inequality comparisons, and the effect of the <<Order clause>>.

For numeric types, and for date, time, and datetime types, the total order is unique and completely determined by the semantics of the type. Jakarta Query implementations must sort these types according to their natural order, that is, the order must agree with the order defined by Java.

Boolean values must be ordered so that `false < true` is satisfied.

For other types, there is at least some freedom in the choice of order. Usually, the order is determined by the native semantics of the database. Note that:

- Textual data is represented in Java as the type `java.lang.String`. Strings are in general ordered lexicographically, but the ordering also depends on the character set and collation used by the database server. Applications must not assume that the order agrees with the `compareTo()` method of `java.lang.String`. In evaluating an inequality involving string operands, an implementation of Jakarta Query is not required to emulate Java collation.

- Binary data is represented in Java as the type `byte[]`. Binary data is in general ordered lexicographically with respect to the constituent bytes. However, since this ordering is rarely meaningful, this specification does not require implementations of Jakarta Query to respect it.

- This specification does not define an order for the sorting of Java `enum` values, which is provider-dependent. An implementation of Jakarta Query might allow control over the order of `enum` values. For example, Jakarta Persistence allows this via the `@Enumerated` annotation.

- This specification does not define an order for UUID values, which is provider-dependent.

[WARNING]
====
When using NoSQL databases, sorting support varies by database type:

Key-value databases:: Sorting of results is not supported.

Wide-column databases:: Support for sorting of results is not required. In general, sorting is not natively supported. When sorting is available, it is typically limited to:
* The key attribute, defined by an annotation such as `jakarta.nosql.Id`.
* Fields that are indexed as secondary indexes.

Graph and document databases:: Support for sorting by a single entity attribute is required. Support for compound sorting (sorting by multiple entity attributes) is not required and may vary due to:
* Potential instability with tied values, where sorting for equivalent values may differ across queries.
* Schema flexibility and mixed data types.
* Dependence on indexes and internal storage order, requiring proper indexing to ensure predictable sorting.
* The distributed nature of sharded clusters, where sorting across shards may introduce additional complexity.

====

=== Logical operators

The logical operators are `and`, `or`, and `not`.

- An `and` operator expression is satisfied if and only if both its operands are satisfied.
- An `or` operator expression is satisfied if at least one of its operands is satisfied.
- A `not` operator expression is never satisfied if its operand _is_ satisfied.

This specification leaves undefined the interpretation of the `not` operator when its operand _is not_ satisfied.

CAUTION: A compliant implementation of Jakarta Query might feature SQL/JPQL-style ternary logic, where `not n > 0` is an unsatisfied logical expression when `n` evaluates to null, or it might feature binary logic where the same expression is considered satisfied. Application programmers should take great care when using the `not` operator with scalar expressions involving `null` values.

Syntactically, logical operators are parsed with lower precedence than <<Equality and inequality operators,equality and inequality operators>> and other <<Conditional expressions,conditional expressions listed above>>. The `not` operator has higher precedence than `and` and `or`. The `and` operator has higher precedence than `or`.

[WARNING]
====
When using NoSQL databases, the support for restrictions varies depending on the database type:

Key-value databases:: Support for the equality restriction is required for the `Id` attribute. There is no requirement to support other types of restrictions or restrictions on other entity attributes.
Wide-column databases:: Wide-column databases are not required to support the `AND` operator or the `OR` operator. Restrictions must be supported for the key attribute that is annotated with `jakarta.nosql.Id`. Support for restrictions on other attributes is not required. Typically they can be used if they are indexed as secondary indexes, although support varies by database provider.
Graph and document databases:: The `AND` and `OR` operators and all of the restrictions described in this section must be supported. Precedence between `AND` and `OR` operators is not guaranteed and may vary significantly based on the NoSQL provider.
====
