== Lexical structure

Lexical analysis requires recognition of the following token types:

- keywords (reserved identifiers),
- regular identifiers,
- named and ordinal parameters,
- operators and punctuation characters,
- literal strings, and
- integer and decimal number literals.

=== Identifiers and keywords

An _identifier_ is any legal Java identifier which is not a keyword. Identifiers are case-sensitive: `hello`, `Hello`, and `HELLO` are distinct identifiers.

In the <<syntax,grammar>>, identifiers are labeled with the `IDENTIFIER` token type.

The following identifiers are _keywords_: `abs`, `all`, `and`, `any`, `as`, `asc`, `avg`, `between`, `both`, `by`, `case`, `ceiling`, `class`, `coalesce`, `concat`, `count`, `current_date`, `current_time`, `current_timestamp`, `delete`, `desc`, `distinct`, `else`, `empty`, `end`, `entry`, `escape`, `except`, `exists`, `exp`, `extract`, `false`, `fetch`, `first`, `floor`, `from`, `function`, `group`, `having`, `in`, `index`, `inner`, `intersect`, `is`, `join`, `key`, `leading`, `last`, `left`, `length`, `like`, `local`, `ln`, `locate`, `lower`, `max`, `member`, `min`, `mod`, `new`, `not`, `null`, `nulls`, `nullif`, `object`, `of`, `on`, `or`, `order`, `outer`, `position`, `power`, `replace`, `right`, `round`, `select`, `set`, `sign`, `size`, `some`, `sqrt`, `substring`, `sum`, `then`, `trailing`, `treat`, `trim`, `true`, `type`, `union`, `update`, `upper`, `value`, `when`, `where`.footnote:[Jakarta Persistence reserves the following additional keywords for
future use: `BIT_LENGTH`, `CHAR_LENGTH`, `CHARACTER_LENGTH`, and `UNKNOWN`.].

**TODO:** function names don't really need to be keywords!

Keywords and other reserved identifiers are case-insensitive: `null`, `Null`, and `NULL` are three ways to write the same keyword.

NOTE: Use of a reserved identifier as a regular identifier in a query might be accepted by a given Jakarta Query provider, but such usage is not guaranteed to be portable between providers.

=== Parameters

A _named parameter_ is a legal Java identifier prefixed with the `:` character, for example, `:name`.

An _ordinal parameter_ is a decimal integer prefixed with the `?` character, for example, `?1`.

Ordinal parameters are numbered sequentially, starting with `?1`.

=== Operators and punctuation

The character sequences `+`, `-`, `*`, `/`, `||`, `=`, `<`, `>`, `<>`, `&lt;=`, `>=` are _operators_.

The characters `(`, `)`, and `,` are _punctuation characters_.

=== String literals

A _literal string_ is a character sequence quoted using the character `'`.

A single literal `'` character may be included within a string literal by self-escaping it, that is, by writing `''`. For example, the string literal ``'Furry''s theorem has nothing to do with furries.'`` evaluates to the string `pass:[Furry's theorem has nothing to do with furries.]`.

In the grammar, literal strings are labeled with the `STRING` token type.

=== Numeric literals

In the core language, numeric literals come in two flavors:

- any legal Java decimal literal of type `int` or `long` is an _integer literal_, and
- any legal Java literal of type `float` or `double` is a _decimal literal_.

A suffix `L`, `D`, or `F` may be used to indicate a specific numeric
type:

- `L` means a 64-bit integer,
- `D` means a 64-bit floating-point value, and
- `F` means a 32-bit floating-point value

The suffix is not case-sensitive.

The literal numeric value preceding the suffix must conform to the rules for Java numeric literals established by the Java
Language Specification.

When the suffix is absent:

- a literal with neither exponent nor decimal point is interpreted as a 32-bit integer value, and
- a literal with either an exponent or decimal point is interpreted as a 64-bit floating-point value.

An implementation of Jakarta Query which targets a language other than Java is not required to respect the suffix in a numeric literal.

In the grammar, integer and decimal literals are labeled with the `INTEGER` and `DOUBLE` token types respectively.

NOTE: Jakarta Query does not require support for literals written in octal or hexadecimal.

In the extended language, arbitrary-precision numeric literals are also provided:

- an arbitrary-precision integer literal follows the format of a Java integer literal, but with the explicit suffix `BI`, and with no limit on the number of decimal digits, and
- an arbitrary-precision decimal literal follows the format of a Java floating-point literal, but with the explicit suffix `BD`, and with no limit on the number of decimal digits.

=== Single-character literals

The `#trim_character#` and `#escape_character#` rules allow specification of a single literal character quoted using the `'` character.

In the grammar, such single-character literals are labeled with the `CHARACTER` token type.

=== Whitespace

The characters Space, Horizontal Tab, Line Feed, Form Feed, and Carriage Return are considered whitespace characters and make no contribution to the token stream.

As usual, token recognition is "greedy". Therefore, whitespace must be placed between two tokens when:

- a keyword directly follows an identifier or named parameter,
- an identifier directly follows a keyword or named parameter, or
- a numeric literal directly follows an identifier, keyword, or parameter.
